server:
  port: 8080
  tomcat:
    uri-encoding: utf-8

spring:
  datasource:
    url: jdbc:mysql://123.207.252.249:3306/mysoftware?useSSL=false&characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: mch1021
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计的Filters,去掉监控页面无法统计，"wall"用于防火墙
      filter:
        commons-log:
          connection-logger-name: stat,wall,log4j
  redis:
    host: 123.207.252.249
    port: 6379
  messages:
    basename: i81n.login
  #禁用缓存，一修改就生效，ctrl+F9
  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.bill.system.entity

